author: barryg
database: false
description: EasyTitles
main: me.barryg.EasyTitles.EasyTitles
name: EasyTitles
startup: postworld
version: '1.1'
commands:
   et:
      description: EasyTitles Help
      usage: To use EasyTitles type /<command> help
   title:
      description: EasyTitles Help
      usage: To use EasyTitles type /<command> help
permissions:
    easytitles.admin.*:
        description: Admin permission
        default: op
    easytitles.admin.reload:
        description: Reload EasyTitles config